//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJCSPORT.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int idArticle { get; set; }
        public string article { get; set; }
        public string description { get; set; }
        public string categorie { get; set; }
        public Nullable<double> prix { get; set; }
        public string image { get; set; }
    }
}
